---
title: "09.05_clinical_flu_metadata"
output: html_document
date: "2025-09-05"
---

# load packages
```{r message=FALSE, warning=FALSE}
library(readr)
```

# load in data as csv
```{r}
#H1N1_clinical_md <- read.csv("~/Downloads/H1N1_clinical_md.csv")
#H5N1_clinical_md <- read.csv("~/Downloads/H5N1_clinical_md.csv")
#H3N2_clinical_md <- read.csv("~/Downloads/H3N2_clinical_md.csv")

H1N1_country_my <- read.csv("/Users/camillemazurek2025/Library/CloudStorage/OneDrive-BaylorCollegeofMedicine/Desktop/R Work/R Directory/BCM Work/Tisza/country/H1N1/H1N1_USA.csv")
H3N2_country_my <- read.csv("/Users/camillemazurek2025/Library/CloudStorage/OneDrive-BaylorCollegeofMedicine/Desktop/R Work/R Directory/BCM Work/Tisza/country/H3N2/H3N2_USA.csv")
```

# added a column in the format of month.year in each metadata file
```{r}
# H1N1_clinical_md$Month_Year <- as.Date(H1N1_clinical_md$Collection_Date)
# H1N1_clinical_md$Month_Year <- format(H1N1_clinical_md$Month_Year, "%m.%Y")
# 
# H5N1_clinical_md$Month_Year <- as.Date(H5N1_clinical_md$Collection_Date)
# H5N1_clinical_md$Month_Year <- format(H5N1_clinical_md$Month_Year, "%m.%Y")
# 
# H3N2_clinical_md$Month_Year <- as.Date(H3N2_clinical_md$Collection_Date)
# H3N2_clinical_md$Month_Year <- format(H3N2_clinical_md$Month_Year, "%m.%Y")


# for country data
H1N1_country_my$Month_Year <- as.Date(H1N1_country_my$Collection_Date)
H1N1_country_my$Month_Year <- format(H1N1_country_my$Month_Year, "%m.%Y")

H3N2_country_my$Month_Year <- as.Date(H3N2_country_my$Collection_Date)
H3N2_country_my$Month_Year <- format(H3N2_country_my$Month_Year, "%m.%Y")
```

# export the adjusted metadata
```{r}
# write_tsv(H1N1_clinical_md, "/Users/camillemazurek2025/Downloads/H1N1_clinical_md_my.tsv")
# 
# write_tsv(H5N1_clinical_md, "/Users/camillemazurek2025/Downloads/H5N1_clinical_md_my.tsv")
# 
# write_tsv(H3N2_clinical_md, "/Users/camillemazurek2025/Downloads/H3N2_clinical_md_my.tsv")

# for country data
write_tsv(H1N1_country_my, "/Users/camillemazurek2025/Library/CloudStorage/OneDrive-BaylorCollegeofMedicine/Desktop/R Work/R Directory/BCM Work/Tisza/country/H1N1_country_my.tsv")

write_tsv(H3N2_country_my, "/Users/camillemazurek2025/Library/CloudStorage/OneDrive-BaylorCollegeofMedicine/Desktop/R Work/R Directory/BCM Work/Tisza/country/H3N2_country_my.tsv")
```


